### PR TITLE
Update to gnome 3.36

### PR DESCRIPTION
**Pull request by A6GibKm**
Update shared-modules

### CODE REVIEW

**Comment by darkdragon-001** [comment]
Fixes #7

**Comment by scx** [comment]
I am currently working on Widelands. Over the past month we have had problems with the `iris` driver.
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1071
When I test the new Widelands release, I'll take care of Pinta.

**Comment by A6GibKm** [comment]
The feels when 3.38 gets released in about a few days. :confetti_ball:

**Comment by darkdragon-001** [comment]
> The feels when 3.38 gets released in about a few days.

@A6GibKm 7e71981 :wink:

**Pull request merged**
